"""add name credit

Revision ID: 646aede72110
Revises: a975dd7d91aa
Create Date: 2019-06-01 16:13:59.521771

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '646aede72110'
down_revision = 'a975dd7d91aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transsummary', sa.Column('creditname', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transsummary', 'creditname')
    # ### end Alembic commands ###
