"""add trans

Revision ID: 68ac67079c3e
Revises: 44062a44fb81
Create Date: 2019-05-24 22:30:38.098943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ac67079c3e'
down_revision = '44062a44fb81'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('transsummary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('money', sa.Float(), nullable=True),
    sa.Column('transnum', sa.String(length=20), nullable=True),
    sa.Column('time', sa.String(length=8), nullable=True),
    sa.Column('addr', sa.String(length=200), nullable=True),
    sa.Column('creditcard', sa.String(length=30), nullable=True),
    sa.Column('creditid', sa.String(length=4), nullable=True),
    sa.Column('creditexpmonth', sa.String(length=2), nullable=True),
    sa.Column('creditexpyear', sa.String(length=4), nullable=True),
    sa.Column('paymentstatus', sa.Integer(), nullable=True),
    sa.Column('shipmentstatus', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('transdetail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('trans_id', sa.Integer(), nullable=False),
    sa.Column('prd_id', sa.Integer(), nullable=False),
    sa.Column('count', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prd_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['trans_id'], ['transsummary.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('shopingcart')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopingcart',
    sa.Column('user_id', sa.INTEGER(), nullable=True),
    sa.Column('prd_id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['prd_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.drop_table('transdetail')
    op.drop_table('transsummary')
    # ### end Alembic commands ###
