"""add count to product

Revision ID: 74e4538b97ea
Revises: ccf678fdd477
Create Date: 2019-04-19 20:43:59.081694

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '74e4538b97ea'
down_revision = 'ccf678fdd477'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('products', sa.Column('count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('products', 'count')
    # ### end Alembic commands ###
