"""add trans name

Revision ID: a975dd7d91aa
Revises: 68ac67079c3e
Create Date: 2019-05-24 23:13:23.856992

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a975dd7d91aa'
down_revision = '68ac67079c3e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transsummary', sa.Column('shipname', sa.String(length=30), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transsummary', 'shipname')
    # ### end Alembic commands ###
