"""add shopping cart

Revision ID: ccf678fdd477
Revises: a7505d69814d
Create Date: 2019-04-13 18:38:33.167865

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ccf678fdd477'
down_revision = 'a7505d69814d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shopingcart',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('prd_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['prd_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('shopingcart')
    # ### end Alembic commands ###
